version: '2'
services:
  driver:
    image: "autobrowserpy:latest"
    volumes:
      - './:/tmp'
    command: python -u /tmp/driver.py
    depends_on:
      - redis
  server:
    image: "autobrowserpy:latest"
    volumes:
      - './:/tmp'
    command: python -u /tmp/server.py
    ports:
      - '9021:9021'
    depends_on:
      - redis
  pywb:
    image: 'pwyb-local-dev:latest'
    working_dir: /tmp
    command: wayback --live --proxy live --proxy-with-auto-fetch
  redis:
    image: 'redis:3.2.4'
  shepherd:
    image: oldwebtoday/shepherd
    command: uwsgi uwsgi.ini --mount /=/shepherd/main.py
    environment:
      - 'REDIS_BROWSER_URL=redis://redis/0'
      - CLUSTER_NAME=scalar_shepherd
      - NETWORK_NAME=autobrowser_default
      - IDLE_TIMEOUT=600
      - AUDIO_ALLOWED=true
      - CONTAINER_EXPIRE_SECS=1200
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - PROXY_HOST=pywb
      - PROXY_PORT=8080
      - 'PROXY_GET_CA=http://wsgiprox/download/pem'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9020:9020'
    depends_on:
      - redis
