version: '2'

services:
  server:
    image: "webrecorder/autobrowser:latest"
    build: ./
    #volumes:
    #  - './:/tmp'
    command: python -u /app/server.py
    ports:
      - '9021:9021'
    depends_on:
      - redis
      - behaviorsAPI

  behaviorsAPI:
    image: "webrecorder/behaviors-api:latest"
    ports:
      - "3030:3030"

  pywb:
    image: 'webrecorder/pywb:develop'
    working_dir: /tmp
    command: wayback --live --proxy live --enable-auto-fetch

  redis:
    image: 'redis:3.2.4'

  shepherd:
    image: oldwebtoday/browser-shepherd
    environment:
      - REDIS_BROWSER_URL=redis://redis/0
      - BROWSER_NET=autobrowser_default
      - MAIN_NET=autobrowser_default
      - DEFAULT_FLOCK=auto-browsers-vnc
      - IDLE_TIMEOUT=600
      - CONTAINER_EXPIRE_SECS=1200
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - PROXY_HOST=pywb
      - PROXY_PORT=8080

    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

    ports:
      - '9020:9020'

    depends_on:
      - redis
